name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DO_SSH_PRIVATE_KEY }}"

      - name: Deploy to DigitalOcean
        run: |
          ssh -T root@${{ secrets.DO_SERVER_IP }}
          cd app

          git pull origin main

          docker-compose down
          docker-compose build
          docker-compose up -d --remove-orphans

          docker system prune -af
          EOF
